version: "3.8"

services:
  web:
    depends_on: 
      - api
    build: ./Client
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: http://localhost:3000
    develop:
      watch:
        - path: ./Client/package.json
          action: rebuild
        - path: ./Client/package-lock.json
          action: rebuild
        - path: ./Client
          target: /app
          action: sync

  api:
    depends_on: 
      - postgres
      - elasticsearch
      - ollama
    build: ./Server
    ports: 
      - 3000:3000
    env_file:
      - .env
    environment: 
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:password@postgres:5432/github_scanner
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_INDEX_PREFIX: github_scanner
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: http://localhost:3001
    volumes:
      - ./temp:/app/temp
    develop:
      watch:
        - path: ./Server/package.json
          action: rebuild
        - path: ./Server/package-lock.json
          action: rebuild
        - path: ./Server
          target: /app
          action: sync

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: github_scanner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA:  /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d github_scanner"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=elasticsearch
      - cluster.name=github-scanner-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    restart: unless-stopped
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch
    profiles:
      - dev  

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
    driver: local
  elasticsearch_data:
    driver: local
  temp_data:
    driver: local
  ollama_data:
    driver: local

networks:
  default:
    name: github-scanner-network